### ISSUE TITLE
very important issue 

### ISSUE THREAD

**Issue by Maria-2024-beep** [paulhager/MMCL-Tabular-Imaging#21]
Very well,

Would you please help me?

When I run in shell:

`python run.py`

I get the error:

```
In 'config': Could not find 'dataset/cardiac_new'

Available options in 'dataset':
	cardiac
	cardinal_ht_severity
	dvm_all_server
	dvm_all_server_0.01
	dvm_all_server_0.1
Config search path:
	provider=hydra, path=pkg://hydra.conf
	provider=main, path=file:///home/a/Downloads/2/MMCL-Tabular-Imaging-main/configs
	provider=schema, path=structured://
```

When I changed the config.yaml "cardiac_new" to "cardiac" I get another error:

```
Global seed set to 2022
Error executing job with overrides: []
Traceback (most recent call last):
  File "/home/a/Downloads/2/MMCL-Tabular-Imaging-main/run.py", line 85, in control
    run(args)
  File "/home/a/Downloads/2/MMCL-Tabular-Imaging-main/run.py", line 27, in run
    args = prepend_paths(args)
  File "/home/a/Downloads/2/MMCL-Tabular-Imaging-main/utils/utils.py", line 148, in prepend_paths
    db = hparams.data_base
omegaconf.errors.MissingMandatoryValue: Missing mandatory value: data_base
    full_key: data_base
    object_type=dict

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

```

Would you please help me how I can solve this issue?

**Comment by paulhager** [comment]
As stated in the ReadMe:

"Path to folder containing data is set through the data_base argument and then joined with filenames set in the dataset yamls. Best strategy is to take dvm_all_server.yaml as a template and fill in the appropriate filenames."

I recommend reading through the ReadMe in full.
